export const PERMISSION = {
  CONFIGURATION_READ: "CONFIGURATION_READ",
  CONFIGURATION_WRITE: "CONFIGURATION_WRITE",
  DEVICE_READ: "DEVICE_READ",
  DEVICE_MANAGE: "DEVICE_MANAGE",
  ALARM_READ: "ALARM_READ",
  ALARM_ACKNOWLEDGE: "ALARM_ACKNOWLEDGE",
  DASHBOARD_READ: "DASHBOARD_READ",
  USER_MANAGE: "USER_MANAGE",
  REPORT_READ: "REPORT_READ",
  REPORT_EXPORT: "REPORT_EXPORT",
  AUDIT_READ: "AUDIT_READ",
  NOTIFICATION_RECIPIENT_READ: "NOTIFICATION_RECIPIENT_READ",
  NOTIFICATION_RECIPIENT_MANAGE: "NOTIFICATION_RECIPIENT_MANAGE",
} as const;

export const PERMISSIONS = Object.values(PERMISSION);

export type Permission = (typeof PERMISSIONS)[number];
