export const ESCALATION_POLICY_AUDIT_SOURCE = "ESCALATION_POLICY_API";
export const ESCALATION_POLICY_AUDIT_ACTION = {
  CREATED: "ESCALATION_POLICY.CREATED",
  UPDATED: "ESCALATION_POLICY.UPDATED",
  STATUS_UPDATED: "ESCALATION_POLICY.STATUS_UPDATED",
} as const;
