export const NOTIFICATION_RECIPIENT_AUDIT_ACTION = {
  CREATED: "NOTIFICATION_RECIPIENT.CREATED",
  UPDATED: "NOTIFICATION_RECIPIENT.UPDATED",
  STATUS_UPDATED: "NOTIFICATION_RECIPIENT.STATUS_UPDATED",
} as const;
export const NOTIFICATION_RECIPIENT_AUDIT_SOURCE = "NOTIFICATION_RECIPIENT_API";
