import {
  Alert,
  Box,
  Button,
  Card,
  CardContent,
  Divider,
  MenuItem,
  TextField,
  Typography,
} from "@mui/material";
import { useMemo, useState, type FormEvent } from "react";
import type { InstallationContext } from "./contracts";

const telemetryTypes = [
  "TEMPERATURE",
  "HUMIDITY",
  "PRESSURE",
  "CO2",
  "DOOR",
  "OTHER",
] as const;

type TelemetryType = (typeof telemetryTypes)[number];

type DraftTelemetry = {
  code: string;
  name: string;
  type: TelemetryType;
  unit: string;
  deviceId: string;
  channel: number;
};

type DraftArea = {
  code: string;
  name: string;
  telemetries: DraftTelemetry[];
};

type DraftDevice = {
  deviceId: string;
};

export type InstallationBuilderSnapshot = {
  companyName: string;
  sites: Array<{
    code: string;
    name: string;
    location?: string;
    timezone: string;
    areas: Array<{
      code: string;
      name: string;
      telemetries: Array<{
        code: string;
        name: string;
        type: TelemetryType;
        unit: string;
        warningDelaySeconds: number;
        criticalDelaySeconds: number;
        calibrationOffset: number;
      }>;
    }>;
  }>;
  devices: Array<{
    deviceId: string;
    siteCode: string;
    type: string;
    protocol: "mqtt";
    manufacturer: string;
    model: string;
    firmwareVersion: string;
    mappings: Array<{
      areaCode: string;
      telemetryCode: string;
      channel: number;
    }>;
  }>;
};

const copy = {
  en: {
    identity: "Installed customer / site identity",
    identityHelp:
      "Loaded from Windows Setup. These values are authoritative and cannot be re-entered here.",
    customer: "Customer",
    site: "Site",
    installationId: "Installation ID",
    devices: "Device inventory",
    deviceHelp:
      "Logical Device IDs are generated by BIO-EMS before any physical ESP32 is provisioned.",
    addDevice: "Add device",
    remove: "Remove",
    areas: "Monitored areas and telemetries",
    areaName: "Area name",
    addArea: "Add monitored area",
    addTelemetry: "Add telemetry",
    telemetryCode: "Telemetry code",
    telemetryName: "Telemetry name",
    telemetryType: "Type",
    unit: "Unit",
    device: "Mapped device",
    channel: "Channel",
    create: "Create installation draft",
    emptyArea: "Add at least one monitored area.",
    validation:
      "Every area needs at least one telemetry, every telemetry must be mapped, channels must be unique per Device, and every Device must have at least one mapping.",
    inventory: "Configuration inventory",
    mappings: "Mappings",
    noTelemetries: "No telemetries added yet.",
    types: {
      TEMPERATURE: "Temperature",
      HUMIDITY: "Humidity",
      PRESSURE: "Pressure",
      CO2: "Carbon dioxide",
      DOOR: "Door status",
      OTHER: "Other",
    },
  },
  ar: {
    identity: "هوية العميل والموقع المثبتة",
    identityHelp:
      "تم تحميلها من Windows Setup. هذه القيم هي المرجع المعتمد ولا يعاد إدخالها هنا.",
    customer: "العميل",
    site: "الموقع",
    installationId: "رقم التثبيت",
    devices: "سجل الأجهزة",
    deviceHelp:
      "ينشئ BIO-EMS أرقام الأجهزة المنطقية قبل ربط أي ESP32 فعلي.",
    addDevice: "إضافة جهاز",
    remove: "حذف",
    areas: "المناطق المراقبة والقياسات",
    areaName: "اسم المنطقة",
    addArea: "إضافة منطقة مراقبة",
    addTelemetry: "إضافة تليمتري",
    telemetryCode: "كود التليمتري",
    telemetryName: "اسم التليمتري",
    telemetryType: "النوع",
    unit: "الوحدة",
    device: "الجهاز المرتبط",
    channel: "القناة",
    create: "إنشاء مسودة التركيب",
    emptyArea: "أضف منطقة مراقبة واحدة على الأقل.",
    validation:
      "يجب أن تحتوي كل منطقة على تليمتري واحدة على الأقل، وأن تكون كل تليمتري مرتبطة بجهاز، وأن تكون القنوات غير مكررة داخل الجهاز، وأن يكون لكل جهاز Mapping واحد على الأقل.",
    inventory: "سجل التهيئة",
    mappings: "الروابط",
    noTelemetries: "لم تتم إضافة تليمتري بعد.",
    types: {
      TEMPERATURE: "درجة الحرارة",
      HUMIDITY: "الرطوبة",
      PRESSURE: "الضغط",
      CO2: "ثاني أكسيد الكربون",
      DOOR: "حالة الباب",
      OTHER: "أخرى",
    },
  },
} as const;

function nextCode(prefix: string, width: number, values: string[]) {
  const used = new Set(values);
  for (let index = 1; index < 10000; index += 1) {
    const candidate = `${prefix}${String(index).padStart(width, "0")}`;
    if (!used.has(candidate)) return candidate;
  }
  throw new Error("No identifier is available");
}

export function nextAreaCode(areas: DraftArea[]) {
  return nextCode(
    "A",
    2,
    areas.map((area) => area.code),
  );
}

export function nextTelemetryCode(areas: DraftArea[]) {
  return nextCode(
    "S",
    1,
    areas.flatMap((area) =>
      area.telemetries.map((telemetry) => telemetry.code),
    ),
  );
}

export function nextDeviceCode(devices: DraftDevice[]) {
  return nextCode(
    "D",
    3,
    devices.map((device) => device.deviceId),
  );
}

function defaultUnit(type: TelemetryType) {
  if (type === "TEMPERATURE") return "°C";
  if (type === "HUMIDITY") return "%RH";
  if (type === "PRESSURE") return "Pa";
  if (type === "CO2") return "ppm";
  if (type === "DOOR") return "state";
  return "unit";
}

function nextChannel(areas: DraftArea[], deviceId: string) {
  const used = new Set(
    areas.flatMap((area) =>
      area.telemetries
        .filter((telemetry) => telemetry.deviceId === deviceId)
        .map((telemetry) => telemetry.channel),
    ),
  );
  let channel = 1;
  while (used.has(channel)) channel += 1;
  return channel;
}

function validBuilder(areas: DraftArea[], devices: DraftDevice[]) {
  if (areas.length === 0 || devices.length === 0) return false;
  if (areas.some((area) => !area.name.trim() || area.telemetries.length === 0))
    return false;

  const mappedByDevice = new Map<string, number>();
  const channelsByDevice = new Map<string, Set<number>>();

  for (const area of areas) {
    for (const telemetry of area.telemetries) {
      if (
        !telemetry.name.trim() ||
        !telemetry.unit.trim() ||
        !devices.some((device) => device.deviceId === telemetry.deviceId) ||
        !Number.isInteger(telemetry.channel) ||
        telemetry.channel < 1
      ) {
        return false;
      }

      mappedByDevice.set(
        telemetry.deviceId,
        (mappedByDevice.get(telemetry.deviceId) ?? 0) + 1,
      );
      const channels =
        channelsByDevice.get(telemetry.deviceId) ?? new Set<number>();
      if (channels.has(telemetry.channel)) return false;
      channels.add(telemetry.channel);
      channelsByDevice.set(telemetry.deviceId, channels);
    }
  }

  return devices.every((device) => (mappedByDevice.get(device.deviceId) ?? 0) > 0);
}

export function buildSnapshot(
  context: InstallationContext,
  areas: DraftArea[],
  devices: DraftDevice[],
): InstallationBuilderSnapshot {
  return {
    companyName: context.customer.name,
    sites: [
      {
        code: context.site.code,
        name: context.site.name,
        ...(context.site.location ? { location: context.site.location } : {}),
        timezone: context.site.timezone ?? "Africa/Cairo",
        areas: areas.map((area) => ({
          code: area.code,
          name: area.name.trim(),
          telemetries: area.telemetries.map((telemetry) => ({
            code: telemetry.code,
            name: telemetry.name.trim(),
            type: telemetry.type,
            unit: telemetry.unit.trim(),
            warningDelaySeconds: 0,
            criticalDelaySeconds: 0,
            calibrationOffset: 0,
          })),
        })),
      },
    ],
    devices: devices.map((device) => ({
      deviceId: device.deviceId,
      siteCode: context.site.code,
      type: "zone-controller",
      protocol: "mqtt",
      manufacturer: "BIO-EMS",
      model: "BIO-EMS-SC-V1",
      firmwareVersion: "0.1.0-pilot.1",
      mappings: areas.flatMap((area) =>
        area.telemetries
          .filter((telemetry) => telemetry.deviceId === device.deviceId)
          .map((telemetry) => ({
            areaCode: area.code,
            telemetryCode: telemetry.code,
            channel: telemetry.channel,
          })),
      ),
    })),
  };
}

export function InstallationBuilder({
  context,
  language,
  submitting,
  onSubmit,
}: {
  context: InstallationContext;
  language: "en" | "ar";
  submitting: boolean;
  onSubmit: (snapshot: InstallationBuilderSnapshot) => Promise<void>;
}) {
  const text = copy[language];
  const [areas, setAreas] = useState<DraftArea[]>([]);
  const [devices, setDevices] = useState<DraftDevice[]>([{ deviceId: "D001" }]);
  const [areaName, setAreaName] = useState("");
  const [attempted, setAttempted] = useState(false);
  const valid = useMemo(() => validBuilder(areas, devices), [areas, devices]);

  const addArea = () => {
    const name = areaName.trim();
    if (!name) return;
    setAreas((current) => [
      ...current,
      { code: nextAreaCode(current), name, telemetries: [] },
    ]);
    setAreaName("");
  };

  const addTelemetry = (areaCode: string) => {
    setAreas((current) => {
      const code = nextTelemetryCode(current);
      const deviceId = devices[0]?.deviceId ?? "";
      const channel = deviceId ? nextChannel(current, deviceId) : 1;
      return current.map((area) =>
        area.code === areaCode
          ? {
              ...area,
              telemetries: [
                ...area.telemetries,
                {
                  code,
                  name: "",
                  type: "TEMPERATURE",
                  unit: "°C",
                  deviceId,
                  channel,
                },
              ],
            }
          : area,
      );
    });
  };

  const updateTelemetry = (
    areaCode: string,
    telemetryCode: string,
    patch: Partial<DraftTelemetry>,
  ) => {
    setAreas((current) =>
      current.map((area) =>
        area.code === areaCode
          ? {
              ...area,
              telemetries: area.telemetries.map((telemetry) =>
                telemetry.code === telemetryCode
                  ? { ...telemetry, ...patch }
                  : telemetry,
              ),
            }
          : area,
      ),
    );
  };

  const removeTelemetry = (areaCode: string, telemetryCode: string) =>
    setAreas((current) =>
      current.map((area) =>
        area.code === areaCode
          ? {
              ...area,
              telemetries: area.telemetries.filter(
                (telemetry) => telemetry.code !== telemetryCode,
              ),
            }
          : area,
      ),
    );

  const submit = async (event: FormEvent) => {
    event.preventDefault();
    setAttempted(true);
    if (!valid) return;
    await onSubmit(buildSnapshot(context, areas, devices));
  };

  const mappingCount = areas.reduce(
    (count, area) => count + area.telemetries.length,
    0,
  );

  return (
    <Box component="form" onSubmit={(event) => void submit(event)}>
      <Typography sx={{ fontWeight: 700 }}>{text.identity}</Typography>
      <Typography color="text.secondary" variant="body2" sx={{ mb: 2 }}>
        {text.identityHelp}
      </Typography>
      <Box
        sx={{
          display: "grid",
          gap: 2,
          gridTemplateColumns: { xs: "1fr", md: "repeat(3,1fr)" },
          mb: 3,
        }}
      >
        <TextField
          label={text.customer}
          value={`${context.customer.name} (${context.customer.code})`}
          InputProps={{ readOnly: true }}
        />
        <TextField
          label={text.site}
          value={`${context.site.name} (${context.site.code})`}
          InputProps={{ readOnly: true }}
        />
        <TextField
          label={text.installationId}
          value={context.installationId}
          InputProps={{ readOnly: true }}
        />
      </Box>

      <Divider sx={{ my: 2 }} />
      <Typography component="h3" variant="h6">
        {text.devices}
      </Typography>
      <Typography color="text.secondary" variant="body2" sx={{ mb: 2 }}>
        {text.deviceHelp}
      </Typography>
      <Box sx={{ display: "flex", flexWrap: "wrap", gap: 1, mb: 2 }}>
        {devices.map((device) => (
          <Card key={device.deviceId} variant="outlined">
            <CardContent sx={{ py: 1.5, "&:last-child": { pb: 1.5 } }}>
              <Typography sx={{ fontWeight: 800 }}>{device.deviceId}</Typography>
              <Typography variant="caption">BIO-EMS-SC-V1</Typography>
              {devices.length > 1 ? (
                <Button
                  size="small"
                  onClick={() => {
                    setDevices((current) =>
                      current.filter((item) => item.deviceId !== device.deviceId),
                    );
                    setAreas((current) =>
                      current.map((area) => ({
                        ...area,
                        telemetries: area.telemetries.map((telemetry) =>
                          telemetry.deviceId === device.deviceId
                            ? { ...telemetry, deviceId: "" }
                            : telemetry,
                        ),
                      })),
                    );
                  }}
                >
                  {text.remove}
                </Button>
              ) : null}
            </CardContent>
          </Card>
        ))}
        <Button
          variant="outlined"
          onClick={() =>
            setDevices((current) => [
              ...current,
              { deviceId: nextDeviceCode(current) },
            ])
          }
        >
          {text.addDevice}
        </Button>
      </Box>

      <Divider sx={{ my: 2 }} />
      <Typography component="h3" variant="h6" sx={{ mb: 2 }}>
        {text.areas}
      </Typography>
      <Box sx={{ display: "flex", gap: 1, mb: 2 }}>
        <TextField
          fullWidth
          label={text.areaName}
          value={areaName}
          onChange={(event) => setAreaName(event.target.value)}
        />
        <Button variant="outlined" onClick={addArea} disabled={!areaName.trim()}>
          {text.addArea}
        </Button>
      </Box>

      {areas.length === 0 ? (
        <Alert severity="info" sx={{ mb: 2 }}>
          {text.emptyArea}
        </Alert>
      ) : null}

      {areas.map((area) => (
        <Card key={area.code} variant="outlined" sx={{ mb: 2 }}>
          <CardContent>
            <Box
              sx={{
                alignItems: "center",
                display: "flex",
                justifyContent: "space-between",
                gap: 1,
                mb: 2,
              }}
            >
              <Typography component="h4" variant="h6">
                {area.code} — {area.name}
              </Typography>
              <Box sx={{ display: "flex", gap: 1 }}>
                <Button
                  variant="outlined"
                  onClick={() => addTelemetry(area.code)}
                >
                  {text.addTelemetry}
                </Button>
                <Button
                  onClick={() =>
                    setAreas((current) =>
                      current.filter((item) => item.code !== area.code),
                    )
                  }
                >
                  {text.remove}
                </Button>
              </Box>
            </Box>

            {area.telemetries.length === 0 ? (
              <Typography color="text.secondary" variant="body2">
                {text.noTelemetries}
              </Typography>
            ) : null}

            {area.telemetries.map((telemetry) => (
              <Box
                key={telemetry.code}
                sx={{
                  display: "grid",
                  gap: 1.5,
                  gridTemplateColumns: {
                    xs: "1fr",
                    md: "0.7fr 1.5fr 1fr 0.8fr 1fr 0.7fr auto",
                  },
                  mb: 1.5,
                }}
              >
                <TextField
                  label={text.telemetryCode}
                  value={telemetry.code}
                  InputProps={{ readOnly: true }}
                />
                <TextField
                  required
                  label={text.telemetryName}
                  value={telemetry.name}
                  onChange={(event) =>
                    updateTelemetry(area.code, telemetry.code, {
                      name: event.target.value,
                    })
                  }
                />
                <TextField
                  select
                  label={text.telemetryType}
                  value={telemetry.type}
                  onChange={(event) => {
                    const nextType = event.target.value as TelemetryType;
                    updateTelemetry(area.code, telemetry.code, {
                      type: nextType,
                      unit: defaultUnit(nextType),
                    });
                  }}
                >
                  {telemetryTypes.map((type) => (
                    <MenuItem key={type} value={type}>
                      {text.types[type]}
                    </MenuItem>
                  ))}
                </TextField>
                <TextField
                  required
                  label={text.unit}
                  value={telemetry.unit}
                  onChange={(event) =>
                    updateTelemetry(area.code, telemetry.code, {
                      unit: event.target.value,
                    })
                  }
                />
                <TextField
                  select
                  required
                  label={text.device}
                  value={telemetry.deviceId}
                  onChange={(event) => {
                    const nextDeviceId = event.target.value;
                    updateTelemetry(area.code, telemetry.code, {
                      deviceId: nextDeviceId,
                      channel: nextChannel(areas, nextDeviceId),
                    });
                  }}
                >
                  {devices.map((device) => (
                    <MenuItem key={device.deviceId} value={device.deviceId}>
                      {device.deviceId}
                    </MenuItem>
                  ))}
                </TextField>
                <TextField
                  required
                  type="number"
                  label={text.channel}
                  value={telemetry.channel}
                  inputProps={{ min: 1, step: 1 }}
                  onChange={(event) =>
                    updateTelemetry(area.code, telemetry.code, {
                      channel: Number(event.target.value),
                    })
                  }
                />
                <Button
                  onClick={() => removeTelemetry(area.code, telemetry.code)}
                >
                  {text.remove}
                </Button>
              </Box>
            ))}
          </CardContent>
        </Card>
      ))}

      <Alert severity="info" sx={{ mb: 2 }}>
        <Typography sx={{ fontWeight: 700 }}>{text.inventory}</Typography>
        <Typography variant="body2">
          {text.devices}: {devices.map((device) => device.deviceId).join(", ")}
        </Typography>
        <Typography variant="body2">
          {text.mappings}: {mappingCount}
        </Typography>
        {areas.map((area) => (
          <Typography key={area.code} variant="body2">
            {area.code} — {area.name}:{" "}
            {area.telemetries.map((telemetry) => telemetry.code).join(", ") ||
              "—"}
          </Typography>
        ))}
      </Alert>

      {attempted && !valid ? (
        <Alert severity="error" sx={{ mb: 2 }}>
          {text.validation}
        </Alert>
      ) : null}

      <Button type="submit" variant="contained" disabled={submitting || !valid}>
        {text.create}
      </Button>
    </Box>
  );
}
