import {
  Alert,
  Box,
  Button,
  Card,
  CardContent,
  Divider,
  MenuItem,
  TextField,
  Typography,
} from "@mui/material";
import { useMemo, useState, type FormEvent } from "react";
import type { InstallationContext } from "./contracts";
import {
  buildSnapshot,
  builderStateFromSnapshot,
  defaultUnit,
  nextAreaCode,
  nextChannel,
  nextDeviceCode,
  nextTelemetryCode,
  telemetryTypes,
  validBuilder,
  type DraftArea,
  type DraftDevice,
  type DraftTelemetry,
  type InstallationBuilderSnapshot,
  type TelemetryType,
} from "./InstallationBuilder.model";

const copy = {
  en: {
    identity: "Installed customer / site identity",
    identityHelp:
      "Loaded from Windows Setup. These values are authoritative and cannot be re-entered here.",
    customer: "Customer",
    site: "Site",
    installationId: "Host installation ID",
    devices: "Device inventory",
    deviceHelp:
      "Logical Device IDs are generated by BIO-EMS before any physical ESP32 is provisioned.",
    addDevice: "Add device",
    remove: "Remove",
    areas: "Monitored areas and telemetries",
    areaName: "Area name",
    addArea: "Add monitored area",
    addTelemetry: "Add telemetry",
    telemetryCode: "Telemetry code",
    telemetryName: "Telemetry name",
    telemetryType: "Type",
    unit: "Unit",
    device: "Mapped device",
    channel: "Channel",
    create: "Create installation draft",
    emptyArea: "Add at least one monitored area.",
    validation:
      "Every area needs at least one telemetry, every telemetry must be mapped, channels must be unique per Device, and every Device must have at least one mapping.",
    inventory: "Configuration inventory",
    mappings: "Mappings",
    noTelemetries: "No telemetries added yet.",
    types: {
      TEMPERATURE: "Temperature",
      HUMIDITY: "Humidity",
      PRESSURE: "Pressure",
      CO2: "Carbon dioxide",
      DOOR: "Door status",
      OTHER: "Other",
    },
  },
  ar: {
    identity: "هوية العميل والموقع المثبتة",
    identityHelp:
      "تم تحميلها من Windows Setup. هذه القيم هي المرجع المعتمد ولا يعاد إدخالها هنا.",
    customer: "العميل",
    site: "الموقع",
    installationId: "معرّف تثبيت الجهاز المضيف",
    devices: "سجل الأجهزة",
    deviceHelp: "ينشئ BIO-EMS أرقام الأجهزة المنطقية قبل ربط أي ESP32 فعلي.",
    addDevice: "إضافة جهاز",
    remove: "حذف",
    areas: "المناطق المراقبة والقياسات",
    areaName: "اسم المنطقة",
    addArea: "إضافة منطقة مراقبة",
    addTelemetry: "إضافة تليمتري",
    telemetryCode: "كود التليمتري",
    telemetryName: "اسم التليمتري",
    telemetryType: "النوع",
    unit: "الوحدة",
    device: "الجهاز المرتبط",
    channel: "القناة",
    create: "إنشاء مسودة التركيب",
    emptyArea: "أضف منطقة مراقبة واحدة على الأقل.",
    validation:
      "يجب أن تحتوي كل منطقة على تليمتري واحدة على الأقل، وأن تكون كل تليمتري مرتبطة بجهاز، وأن تكون القنوات غير مكررة داخل الجهاز، وأن يكون لكل جهاز Mapping واحد على الأقل.",
    inventory: "سجل التهيئة",
    mappings: "الروابط",
    noTelemetries: "لم تتم إضافة تليمتري بعد.",
    types: {
      TEMPERATURE: "درجة الحرارة",
      HUMIDITY: "الرطوبة",
      PRESSURE: "الضغط",
      CO2: "ثاني أكسيد الكربون",
      DOOR: "حالة الباب",
      OTHER: "أخرى",
    },
  },
} as const;

export function InstallationBuilder({
  context,
  language,
  submitting,
  initialSnapshot,
  submitLabel,
  onSubmit,
}: {
  context: InstallationContext;
  language: "en" | "ar";
  submitting: boolean;
  initialSnapshot?: Record<string, unknown>;
  submitLabel?: string;
  onSubmit: (snapshot: InstallationBuilderSnapshot) => Promise<void>;
}) {
  const text = copy[language];
  const initial = builderStateFromSnapshot(initialSnapshot, context.site.code);
  const [areas, setAreas] = useState<DraftArea[]>(() => initial.areas);
  const [devices, setDevices] = useState<DraftDevice[]>(() => initial.devices);
  const [areaName, setAreaName] = useState("");
  const [attempted, setAttempted] = useState(false);
  const valid = useMemo(() => validBuilder(areas, devices), [areas, devices]);

  const addArea = () => {
    const name = areaName.trim();
    if (!name) return;
    setAreas((current) => [
      ...current,
      { code: nextAreaCode(current), name, telemetries: [] },
    ]);
    setAreaName("");
  };

  const addTelemetry = (areaCode: string) => {
    setAreas((current) => {
      const code = nextTelemetryCode(current);
      const deviceId = devices[0]?.deviceId ?? "";
      const channel = deviceId ? nextChannel(current, deviceId) : 1;
      return current.map((area) =>
        area.code === areaCode
          ? {
              ...area,
              telemetries: [
                ...area.telemetries,
                {
                  code,
                  name: "",
                  type: "TEMPERATURE",
                  unit: "°C",
                  deviceId,
                  channel,
                  warningDelaySeconds: 0,
                  criticalDelaySeconds: 0,
                  calibrationOffset: 0,
                },
              ],
            }
          : area,
      );
    });
  };

  const updateTelemetry = (
    areaCode: string,
    telemetryCode: string,
    patch: Partial<DraftTelemetry>,
  ) => {
    setAreas((current) =>
      current.map((area) =>
        area.code === areaCode
          ? {
              ...area,
              telemetries: area.telemetries.map((telemetry) =>
                telemetry.code === telemetryCode
                  ? { ...telemetry, ...patch }
                  : telemetry,
              ),
            }
          : area,
      ),
    );
  };

  const removeTelemetry = (areaCode: string, telemetryCode: string) =>
    setAreas((current) =>
      current.map((area) =>
        area.code === areaCode
          ? {
              ...area,
              telemetries: area.telemetries.filter(
                (telemetry) => telemetry.code !== telemetryCode,
              ),
            }
          : area,
      ),
    );

  const submit = async (event: FormEvent) => {
    event.preventDefault();
    setAttempted(true);
    if (!valid) return;
    await onSubmit(buildSnapshot(context, areas, devices));
  };

  const mappingCount = areas.reduce(
    (count, area) => count + area.telemetries.length,
    0,
  );

  return (
    <Box component="form" onSubmit={(event) => void submit(event)}>
      <Typography sx={{ fontWeight: 700 }}>{text.identity}</Typography>
      <Typography color="text.secondary" variant="body2" sx={{ mb: 2 }}>
        {text.identityHelp}
      </Typography>
      <Box
        sx={{
          display: "grid",
          gap: 2,
          gridTemplateColumns: { xs: "1fr", md: "repeat(3,1fr)" },
          mb: 3,
        }}
      >
        <TextField
          label={text.customer}
          value={`${context.customer.name} (${context.customer.code})`}
          slotProps={{ htmlInput: { readOnly: true } }}
        />
        <TextField
          label={text.site}
          value={`${context.site.name} (${context.site.code})`}
          slotProps={{ htmlInput: { readOnly: true } }}
        />
        <TextField
          label={text.installationId}
          value={context.installationId}
          slotProps={{ htmlInput: { readOnly: true } }}
        />
      </Box>

      <Divider sx={{ my: 2 }} />
      <Typography component="h3" variant="h6">
        {text.devices}
      </Typography>
      <Typography color="text.secondary" variant="body2" sx={{ mb: 2 }}>
        {text.deviceHelp}
      </Typography>
      <Box sx={{ display: "flex", flexWrap: "wrap", gap: 1, mb: 2 }}>
        {devices.map((device) => (
          <Card key={device.deviceId} variant="outlined">
            <CardContent sx={{ py: 1.5, "&:last-child": { pb: 1.5 } }}>
              <Typography sx={{ fontWeight: 800 }}>
                {device.deviceId}
              </Typography>
              <Typography variant="caption">BIO-EMS-SC-V1</Typography>
              <TextField
                select
                size="small"
                sx={{ display: "block", mt: 1, minWidth: 190 }}
                label={
                  language === "ar"
                    ? "وحدات SIM-D4 المركبة"
                    : "Fitted SIM-D4 modules"
                }
                value={device.simModules ?? 1}
                onChange={(event) =>
                  setDevices((current) =>
                    current.map((item) =>
                      item.deviceId === device.deviceId
                        ? { ...item, simModules: Number(event.target.value) }
                        : item,
                    ),
                  )
                }
              >
                {[1, 2, 3, 4].map((count) => (
                  <MenuItem key={count} value={count}>
                    {count} SIM · {count * 4}{" "}
                    {language === "ar" ? "قنوات" : "channels"}
                  </MenuItem>
                ))}
              </TextField>
              {devices.length > 1 ? (
                <Button
                  size="small"
                  onClick={() => {
                    setDevices((current) =>
                      current.filter(
                        (item) => item.deviceId !== device.deviceId,
                      ),
                    );
                    setAreas((current) =>
                      current.map((area) => ({
                        ...area,
                        telemetries: area.telemetries.map((telemetry) =>
                          telemetry.deviceId === device.deviceId
                            ? { ...telemetry, deviceId: "" }
                            : telemetry,
                        ),
                      })),
                    );
                  }}
                >
                  {text.remove}
                </Button>
              ) : null}
            </CardContent>
          </Card>
        ))}
        <Button
          variant="outlined"
          onClick={() =>
            setDevices((current) => [
              ...current,
              { deviceId: nextDeviceCode(current), simModules: 1 },
            ])
          }
        >
          {text.addDevice}
        </Button>
      </Box>

      <Divider sx={{ my: 2 }} />
      <Typography component="h3" variant="h6" sx={{ mb: 2 }}>
        {text.areas}
      </Typography>
      <Box sx={{ display: "flex", gap: 1, mb: 2 }}>
        <TextField
          fullWidth
          label={text.areaName}
          value={areaName}
          onChange={(event) => setAreaName(event.target.value)}
        />
        <Button
          variant="outlined"
          onClick={addArea}
          disabled={!areaName.trim()}
        >
          {text.addArea}
        </Button>
      </Box>

      {areas.length === 0 ? (
        <Alert severity="info" sx={{ mb: 2 }}>
          {text.emptyArea}
        </Alert>
      ) : null}

      {areas.map((area) => (
        <Card key={area.code} variant="outlined" sx={{ mb: 2 }}>
          <CardContent>
            <Box
              sx={{
                alignItems: "center",
                display: "flex",
                justifyContent: "space-between",
                gap: 1,
                mb: 2,
              }}
            >
              <Typography component="h4" variant="h6">
                {area.code} — {area.name}
              </Typography>
              <Box sx={{ display: "flex", gap: 1 }}>
                <Button
                  variant="outlined"
                  onClick={() => addTelemetry(area.code)}
                >
                  {text.addTelemetry}
                </Button>
                <Button
                  onClick={() =>
                    setAreas((current) =>
                      current.filter((item) => item.code !== area.code),
                    )
                  }
                >
                  {text.remove}
                </Button>
              </Box>
            </Box>

            {area.telemetries.length === 0 ? (
              <Typography color="text.secondary" variant="body2">
                {text.noTelemetries}
              </Typography>
            ) : null}

            {area.telemetries.map((telemetry) => (
              <Box
                key={telemetry.code}
                sx={{
                  display: "grid",
                  gap: 1.5,
                  gridTemplateColumns: {
                    xs: "1fr",
                    md: "0.7fr 1.5fr 1fr 0.8fr 1fr 0.7fr auto",
                  },
                  mb: 1.5,
                }}
              >
                <TextField
                  label={text.telemetryCode}
                  value={telemetry.code}
                  slotProps={{ htmlInput: { readOnly: true } }}
                />
                <TextField
                  required
                  label={text.telemetryName}
                  value={telemetry.name}
                  onChange={(event) =>
                    updateTelemetry(area.code, telemetry.code, {
                      name: event.target.value,
                    })
                  }
                />
                <TextField
                  select
                  label={text.telemetryType}
                  value={telemetry.type}
                  onChange={(event) => {
                    const nextType = event.target.value as TelemetryType;
                    updateTelemetry(area.code, telemetry.code, {
                      type: nextType,
                      unit: defaultUnit(nextType),
                    });
                  }}
                >
                  {telemetryTypes.map((type) => (
                    <MenuItem key={type} value={type}>
                      {text.types[type]}
                    </MenuItem>
                  ))}
                </TextField>
                <TextField
                  required
                  label={text.unit}
                  value={telemetry.unit}
                  onChange={(event) =>
                    updateTelemetry(area.code, telemetry.code, {
                      unit: event.target.value,
                    })
                  }
                />
                <TextField
                  select
                  required
                  label={text.device}
                  value={telemetry.deviceId}
                  onChange={(event) => {
                    const nextDeviceId = event.target.value;
                    updateTelemetry(area.code, telemetry.code, {
                      deviceId: nextDeviceId,
                      channel: nextChannel(areas, nextDeviceId),
                    });
                  }}
                >
                  {devices.map((device) => (
                    <MenuItem key={device.deviceId} value={device.deviceId}>
                      {device.deviceId}
                    </MenuItem>
                  ))}
                </TextField>
                <TextField
                  required
                  type="number"
                  label={text.channel}
                  value={telemetry.channel}
                  helperText={
                    language === "ar"
                      ? "1–4: SIM1، 5–8: SIM2، 9–12: SIM3، 13–16: SIM4"
                      : "1–4: SIM1; 5–8: SIM2; 9–12: SIM3; 13–16: SIM4"
                  }
                  slotProps={{
                    htmlInput: {
                      min: 1,
                      max:
                        (devices.find(
                          (device) => device.deviceId === telemetry.deviceId,
                        )?.simModules ?? 4) * 4,
                      step: 1,
                    },
                  }}
                  onChange={(event) =>
                    updateTelemetry(area.code, telemetry.code, {
                      channel: Number(event.target.value),
                    })
                  }
                />
                {telemetry.type === "TEMPERATURE" ? (
                  <Box
                    sx={{
                      gridColumn: "1 / -1",
                      display: "grid",
                      gap: 1,
                      gridTemplateColumns: {
                        xs: "1fr 1fr",
                        md: "repeat(4, 1fr)",
                      },
                    }}
                  >
                    {(
                      [
                        [
                          "alarmLow",
                          language === "ar" ? "إنذار منخفض °C" : "Low alarm °C",
                        ],
                        [
                          "warningLow",
                          language === "ar"
                            ? "تحذير منخفض °C"
                            : "Low warning °C",
                        ],
                        [
                          "warningHigh",
                          language === "ar"
                            ? "تحذير مرتفع °C"
                            : "High warning °C",
                        ],
                        [
                          "alarmHigh",
                          language === "ar"
                            ? "إنذار مرتفع °C"
                            : "High alarm °C",
                        ],
                      ] as const
                    ).map(([field, label]) => (
                      <TextField
                        key={field}
                        type="number"
                        label={label}
                        value={telemetry[field] ?? ""}
                        slotProps={{ htmlInput: { step: "any" } }}
                        onChange={(event) =>
                          updateTelemetry(area.code, telemetry.code, {
                            [field]:
                              event.target.value === ""
                                ? undefined
                                : Number(event.target.value),
                          })
                        }
                      />
                    ))}
                  </Box>
                ) : null}
                <Button
                  onClick={() => removeTelemetry(area.code, telemetry.code)}
                >
                  {text.remove}
                </Button>
              </Box>
            ))}
          </CardContent>
        </Card>
      ))}

      <Alert severity="info" sx={{ mb: 2 }}>
        <Typography sx={{ fontWeight: 700 }}>{text.inventory}</Typography>
        <Typography variant="body2">
          {text.devices}: {devices.map((device) => device.deviceId).join(", ")}
        </Typography>
        <Typography variant="body2">
          {text.mappings}: {mappingCount}
        </Typography>
        {areas.map((area) => (
          <Typography key={area.code} variant="body2">
            {area.code} — {area.name}:{" "}
            {area.telemetries.map((telemetry) => telemetry.code).join(", ") ||
              "—"}
          </Typography>
        ))}
      </Alert>

      {attempted && !valid ? (
        <Alert severity="error" sx={{ mb: 2 }}>
          {text.validation}
        </Alert>
      ) : null}

      <Button type="submit" variant="contained" disabled={submitting || !valid}>
        {submitLabel ?? text.create}
      </Button>
    </Box>
  );
}
