export enum AlarmStatus {
  CRITICAL_LOW = "CRITICAL_LOW",
  WARNING_LOW = "WARNING_LOW",
  NORMAL = "NORMAL",
  WARNING_HIGH = "WARNING_HIGH",
  CRITICAL_HIGH = "CRITICAL_HIGH",
  UNKNOWN = "UNKNOWN",
}
