import PDFDocument from "pdfkit";
import type { OperationalReportService } from "./operational-report.service";

type Result = Awaited<ReturnType<OperationalReportService["preview"]>>;

export async function renderOperationalPdf(result: Result, generatedBy: string): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 45, size: "A4" });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk) => chunks.push(Buffer.from(chunk)));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
    doc.font("Helvetica-Bold").fontSize(18).text(`BIO-EMS ${result.identity.reportType}`);
    doc.font("Helvetica").fontSize(9).moveDown().text(`Report ID: ${result.identity.reportId}`);
    doc.text(`Generated by: ${generatedBy}`);
    doc.text(`Range: ${result.scope.from} to ${result.scope.to}`);
    doc.text(`Records: ${result.summary.records}`).moveDown();
    for (const record of result.records) {
      if (doc.y > 740) doc.addPage();
      doc
        .font("Helvetica")
        .fontSize(8)
        .text(
          Object.entries(record)
            .map(([key, value]) => `${key}: ${value ?? "—"}`)
            .join(" | ")
        )
        .moveDown(0.4);
    }
    if (result.records.length === 0) doc.text("No records in the selected range.");
    doc.end();
  });
}

export function operationalPdfFilename(result: Result): string {
  return `bio-ems_${result.identity.reportType.toLowerCase()}_${result.scope.from.slice(0, 10)}_${result.scope.to.slice(0, 10)}.pdf`;
}
