import type { OperationalReportService } from "./operational-report.service";

type Result = Awaited<ReturnType<OperationalReportService["preview"]>>;
const csv = (value: unknown) => `"${String(value ?? "").replaceAll('"', '""')}"`;

export function renderOperationalCsv(result: Result, generatedBy: string): string {
  const columns = Array.from(new Set(result.records.flatMap((record) => Object.keys(record))));
  return [
    csv(`BIO-EMS ${result.identity.reportType} Report`),
    `${csv("Report ID")},${csv(result.identity.reportId)}`,
    `${csv("Generated by")},${csv(generatedBy)}`,
    `${csv("Range")},${csv(result.scope.from)},${csv(result.scope.to)}`,
    "",
    columns.map(csv).join(","),
    ...result.records.map((record) => columns.map((column) => csv(record[column])).join(",")),
  ].join("\r\n");
}

export function operationalCsvFilename(result: Result): string {
  return `bio-ems_${result.identity.reportType.toLowerCase()}_${result.scope.from.slice(0, 10)}_${result.scope.to.slice(0, 10)}.csv`;
}
