import PDFDocument from "pdfkit";
import type { OperationalReportService } from "./operational-report.service";

type Result = Awaited<ReturnType<OperationalReportService["preview"]>>;
const MARGIN = 44;
const TITLES = {
  "ALARM-HISTORY": "Alarm History",
  "DEVICE-HEALTH": "Device Communication Health",
  "AUDIT-OPERATIONS": "Audit and Operations",
} as const;

function printable(value: unknown, timeZone: string): string {
  if (value === null || value === undefined || value === "") return "—";
  if (typeof value === "string" && /^\d{4}-\d{2}-\d{2}T/.test(value)) {
    const date = new Date(value);
    if (!Number.isNaN(date.valueOf())) {
      return new Intl.DateTimeFormat("en-GB", {
        dateStyle: "medium",
        timeStyle: "medium",
        timeZone,
      }).format(date);
    }
  }
  return String(value);
}

function safe(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function heading(doc: PDFKit.PDFDocument, value: string) {
  doc.moveDown(0.7).font("Helvetica-Bold").fontSize(12).fillColor("#174a5c").text(value);
  doc.moveDown(0.35);
}

function keyValue(doc: PDFKit.PDFDocument, label: string, value: unknown, timeZone: string) {
  const y = doc.y;
  doc
    .font("Helvetica-Bold")
    .fontSize(8)
    .fillColor("#263238")
    .text(label, MARGIN, y, { width: 125 });
  doc
    .font("Helvetica")
    .fillColor("#37474f")
    .text(printable(value, timeZone), MARGIN + 130, y, {
      width: doc.page.width - MARGIN * 2 - 130,
    });
  doc.y = Math.max(doc.y, y + 14);
}

export async function renderOperationalPdf(result: Result, generatedBy: string): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const title = TITLES[result.identity.reportType];
    const doc = new PDFDocument({
      margin: MARGIN,
      size: "A4",
      bufferPages: true,
      info: { Title: `BIO-EMS ${title}`, Author: generatedBy, Creator: "BIO-EMS" },
    });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.rect(0, 0, doc.page.width, 82).fill("#0f3d4c");
    doc.font("Helvetica-Bold").fontSize(21).fillColor("#ffffff").text("BIO-EMS", MARGIN, 24);
    doc.fontSize(14).text(`${title} Report`, MARGIN, 50);
    doc.y = 102;

    heading(doc, "Report identity and scope");
    keyValue(doc, "Report ID", result.identity.reportId, result.scope.timeZone);
    keyValue(doc, "Generated by", generatedBy, result.scope.timeZone);
    keyValue(doc, "Generated at", result.provenance.generatedAt, result.scope.timeZone);
    keyValue(doc, "From", result.scope.from, result.scope.timeZone);
    keyValue(doc, "To", result.scope.to, result.scope.timeZone);
    keyValue(doc, "Site time zone", result.scope.timeZone, result.scope.timeZone);
    keyValue(
      doc,
      "Sensor scope",
      `${result.scope.sensorUuids.length} selected sensor(s)`,
      result.scope.timeZone
    );
    keyValue(doc, "Evidence source", result.provenance.source, result.scope.timeZone);

    heading(doc, "Executive summary");
    keyValue(doc, "Total records", result.summary.records, result.scope.timeZone);
    for (const [status, count] of Object.entries(result.summary.resultCounts)) {
      keyValue(doc, status.replaceAll("_", " "), count, result.scope.timeZone);
    }

    heading(doc, "Data quality and disclosure");
    keyValue(doc, "Complete", result.quality.complete ? "Yes" : "No", result.scope.timeZone);
    keyValue(doc, "Warnings", result.quality.warnings.join("; ") || "None", result.scope.timeZone);

    heading(doc, "Evidence records");
    if (result.records.length === 0)
      doc
        .font("Helvetica-Oblique")
        .fontSize(9)
        .fillColor("#546e7a")
        .text("No records in the selected range.");
    result.records.forEach((record, index) => {
      const body = Object.entries(record)
        .map(
          ([key, value]) =>
            `${key.replaceAll("_", " ")}: ${printable(value, result.scope.timeZone)}`
        )
        .join("   |   ");
      const height = Math.max(
        28,
        doc.heightOfString(body, { width: doc.page.width - MARGIN * 2 - 16 }) + 15
      );
      if (doc.y + height > doc.page.height - MARGIN - 28) doc.addPage();
      const y = doc.y;
      doc
        .roundedRect(MARGIN, y, doc.page.width - MARGIN * 2, height, 3)
        .fill(index % 2 ? "#f7fafb" : "#eef5f7");
      doc
        .font("Helvetica")
        .fontSize(7)
        .fillColor("#263238")
        .text(body, MARGIN + 8, y + 7, {
          width: doc.page.width - MARGIN * 2 - 16,
        });
      doc.y = y + height + 4;
    });

    const pages = doc.bufferedPageRange();
    for (let index = 0; index < pages.count; index += 1) {
      doc.switchToPage(index);
      doc
        .font("Helvetica")
        .fontSize(7)
        .fillColor("#546e7a")
        .text(
          `BIO-EMS · ${title} · Controlled copy · Page ${index + 1}`,
          MARGIN,
          doc.page.height - 35,
          { width: doc.page.width - MARGIN * 2, align: "center", lineBreak: false }
        );
    }
    doc.end();
  });
}

export function operationalPdfFilename(result: Result): string {
  return `bio-ems_${safe(result.identity.reportType)}_${result.scope.from.slice(0, 10)}_${result.scope.to.slice(0, 10)}.pdf`;
}
