export function temperaturePerformanceCsvFilename(
  report: {
    identity: {
      reportType: string;
    };
  },
): string {
  return `${report.identity.reportType.toLowerCase()}-${new Date()
    .toISOString()
    .slice(0, 10)}.csv`;
}

function escapeCsv(value: unknown): string {
  if (value === null || value === undefined) {
    return "";
  }

  const text = String(value);

  if (
    text.includes(",") ||
    text.includes('"') ||
    text.includes("\n")
  ) {
    return `"${text.replaceAll('"', '""')}"`;
  }

  return text;
}

export function renderTemperaturePerformanceCsv(
  report: {
    identity: {
      reportType: string;
      contractVersion: string;
    };

    scope: {
      sensorUuids: string[];
      from: string;
      to: string;
      timeZone: string;
      language: string;
    };

    provenance: {
      generatedAt: string;
      source: string;
      rangeSemantics: string;
    };

    quality: {
      complete: boolean;
      warnings: string[];
      unavailableSections: string[];
    };

    sensors: Array<{
      sensor: string;
      unit: string;
      records: number;
      minimum: number | null;
      maximum: number | null;
      average: number | null;
      firstReadingAt: string | null;
      lastReadingAt: string | null;
    }>;

    summary: {
      sensors: number;
      records: number;
      minimum: number | null;
      maximum: number | null;
      average: number | null;
    };
  },
  generatedBy: string,
): string {
  const rows: string[][] = [];

  rows.push([
    "BIO-EMS Temperature Performance Report",
  ]);

  rows.push([]);

  rows.push([
    "Report Type",
    report.identity.reportType,
  ]);

  rows.push([
    "Contract Version",
    report.identity.contractVersion,
  ]);

  rows.push([
    "Generated At",
    report.provenance.generatedAt,
  ]);

  rows.push([
    "Generated By",
    generatedBy,
  ]);

  rows.push([]);

  rows.push([
    "Sensor Count",
    String(report.summary.sensors),
  ]);

  rows.push([
    "Total Records",
    String(report.summary.records),
  ]);

  rows.push([
    "Minimum",
    String(report.summary.minimum ?? ""),
  ]);

  rows.push([
    "Maximum",
    String(report.summary.maximum ?? ""),
  ]);

  rows.push([
    "Average",
    String(report.summary.average ?? ""),
  ]);

  rows.push([]);

  rows.push([
    "Sensor",
    "Unit",
    "Records",
    "Minimum",
    "Maximum",
    "Average",
    "First Reading",
    "Last Reading",
  ]);

  for (const sensor of report.sensors) {
    rows.push([
      sensor.sensor,
      sensor.unit,
      String(sensor.records),
      String(sensor.minimum ?? ""),
      String(sensor.maximum ?? ""),
      String(sensor.average ?? ""),
      sensor.firstReadingAt ?? "",
      sensor.lastReadingAt ?? "",
    ]);
  }

  return rows
    .map((row) =>
      row.map(escapeCsv).join(","),
    )
    .join("\n");
}