### Health
GET http://localhost:3001/api/v1/health

###

POST http://localhost:3001/api/v1/sites
Content-Type: application/json

{
    "code":"SITE001",
    "name":"Main Warehouse",
    "location":"Tanta",
    "timezone":"Africa/Cairo"
}

###

GET http://localhost:3001/api/v1/sites